import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-product',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './product.component.html',
  styleUrl: './product.component.css'
})
export class ProductComponent {
products=[
  {
    name: 'Nước Tẩy Trang La Roche Posay 400ml Da Dầu Da Và Nhạy Cảm',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Nước Tẩy Trang La Roche Posay 400ml Da Dầu Da Và Nhạy Cảm',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Nước uống colagen Nước Tẩy Trang La Roche Posay 400ml Da Dầu Da Và Nhạy Cảm',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Chuột Máy Tính Không Dây Bluetooth Ziyou X2 PRO VIP Mouse LED RGB cho Máy tính, Laptop PC',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Chuột Máy Tính Không Dây Bluetooth Ziyou X2 PRO VIP Mouse LED RGB cho Máy tính, Laptop PC',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Chuột Gaming Không Dây Bluetooth Attack Shark X11 Chip PRO PAW3311 Có Dock Sạc LED, 22000 DPI',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Chuột Gaming Không Dây Bluetooth Attack Shark X11 Chip PRO PAW3311 Có Dock Sạc LED, 22000 DPI',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',

  },
  {
    name: 'Thời trang nam',
    url: '../../assets/products/product3.jpg',
    alt: 'Thời trang nam',
    cost: 418000,
    soldOut: 'Đã bán 1000+',
  },
]


}
